/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginsystem;

import java.io.FileNotFoundException;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author edwar
 */
public class LoginForm extends javax.swing.JFrame {

    private boolean isLogin = true;
    private final String def = "";

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        //initialize
        email.setVisible(false);
        emailText.setVisible(false);
        res.setText(def);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        res = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration System");
        setLocation(new java.awt.Point(300, 90));

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setText("Login Form");

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setText("Username");

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setText("Password");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        switchButton.setText("Forget Password");
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setText("Email");

        res.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        res.setText("Response");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton)
                                .addGap(26, 26, 26)
                                .addComponent(switchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(closeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(password)
                                    .addComponent(email))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(passText)
                                    .addComponent(emailText))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(title)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(resetButton)
                    .addComponent(closeButton)
                    .addComponent(switchButton))
                .addGap(33, 33, 33)
                .addComponent(res)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        // System.out.println(evt);
        //reset all text
        usernameText.setText(def);
        passText.setText(def);
        emailText.setText(def);
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        // System.out.println(evt);
        RegisterSys register = new RegisterSys();
        try {
            register.loadUsers();
        } catch (FileNotFoundException | ParseException exp) {
            System.out.println(exp);
        }

        // error buffer
        StringBuilder errbuf = new StringBuilder();

        // check action of button
        // get data from sign-up form
        String username = usernameText.getText();
        String passStr = new String(passText.getPassword());
        String emailStr = emailText.getText();

        // check input value of username, password or email 
        if (username.isEmpty()) {
            errbuf.append("User ID is empty..\n");
        } else if (register.getUser(username) == null) {
            errbuf.append("User " + username + " does not exist.. \n");
        } else {
            User user = register.getUser(username);
            //check password or email
            if (isLogin) {
                if (passStr.isEmpty()) {
                    errbuf.append("Password is empty..\n");
                } else {
                    Encrypter secret = new Encrypter();
                    String securedPassword = secret.sha256(passStr);
                    if (!securedPassword.equals(user.getPassword())) {
                        errbuf.append("Password does not match..\n");
                    }
                }
            } else {
                if (emailStr.isEmpty()) {
                    errbuf.append("Email is empty..\n");
                } else if (!emailStr.equals(user.getEmail())) {
                    System.out.println(user.getEmail());
                    errbuf.append("Email does not match..\n");
                }
            }
        }

        // display error
        if (errbuf.length() > 0) {
            JOptionPane.showMessageDialog(this, errbuf.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // login ok, disable Edit
            usernameText.setEditable(false);
            usernameText.setEnabled(false);
            submitButton.setEnabled(false);
            submitButton.setVisible(false);
            resetButton.setEnabled(false);
            resetButton.setVisible(false);
            switchButton.setEnabled(false);
            switchButton.setVisible(false);

            if (isLogin) {
                passText.setEditable(false);
                passText.setEnabled(false);
                res.setText("Login Successfully..");

            } else {
                emailText.setEditable(false);
                emailText.setEnabled(false);
                // generate a temp password
                PassChecker passtool = new PassChecker();
                String tempPass = passtool.generatePassword(12);
                //save temp password
                register.saveTempPass(username, tempPass);
                //send temp password - it does not work
                //display in response message
                res.setText("A temp password \"" + tempPass + "\" was sent to you..");
            }

        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
        // System.out.println(evt);
        if (isLogin) {
            isLogin = false;
            switchButton.setText(UserConfig.BACK_LOGIN);
            password.setVisible(false);
            passText.setVisible(false);
            email.setVisible(true);
            emailText.setVisible(true);
            title.setText(UserConfig.FORM_FORGET_PASS);

        } else {
            isLogin = true;
            switchButton.setText(UserConfig.FORGET_PASS);
            password.setVisible(true);
            passText.setVisible(true);
            email.setVisible(false);
            emailText.setVisible(false);
            title.setText(UserConfig.FORM_LOGIN);
        }
    }//GEN-LAST:event_switchButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        // System.out.println(evt);
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailText;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel password;
    private javax.swing.JLabel res;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
